name: Close Stale Issues

on:
  schedule:
    - cron: '10 13 * * 1'  # Run Weekly Monday

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not been updated for over 3 years and will be marked as stale. If the issue still exists, please comment or update the issue, otherwise it will be closed after 7 days.'
        close-issue-message: 'This issue has been automatically closed due to inactivity. If the issue still exists, please reopen it.'
        days-before-issue-stale: 1095
        days-before-issue-close: 7
        stale-issue-label: 'Stale'
        exempt-issue-labels: 'pinned,security'
        operations-per-run: 100
